name: 'Deploy to ACR'
description: 'Builds Docker image and pushes it to Azure Container Registry'
inputs:
  acr-repository:
    description: 'ACR login server (e.g., myregistry.azurecr.io)'
    required: true
  acr-username:
    description: 'ACR username'
    required: true
  acr-admin-token:
    description: 'ACR password (use a secret)'
    required: true
  image-name:
    description: 'Image name (e.g., myapp)'
    required: true
  image-tag:
    description: 'Image tag (e.g., latest)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to ACR
      run: echo "${{ inputs.acr-admin-token }}" | docker login ${{ inputs.acr-repository }} -u ${{ inputs.acr-username }} --password-stdin
      shell: bash
    - name: List target contents
      run: ls -lh target/
      shell: bash
    - name: Build Docker image
      run: docker build -t ${{ inputs.acr-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }} .
      shell: bash
    - name: Push Docker image
      run: docker push ${{ inputs.acr-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
