name: Maven Build

on:
  push:
    branches:
      - main # or your target branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: "korebhaumik"
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # or 'zulu', 'adopt', etc.
          java-version: "21" # or 11, 21 based on your project

      - name: Copy custom settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/settings.xml

      - name: Build with Maven using custom settings
        run: mvn -X clean install --settings ~/.m2/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_id }}
          release_name: Maven Artifact ${{ github.run_id }}
          draft: false
          prerelease: false
#
#      - name: Upload JAR to Release
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./target/todo-0.0.1-SNAPSHOT.jar
#          asset_name: todo-0.0.1-SNAPSHOT.jar
#          asset_content_type: application/java-archive
