name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    # Maven Build
      - uses: ./.github/actions/maven-build
        with:
          java-version: '21'
    
    # Upload Maven artifact
      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ./target/*.jar

    # Download artifact (simulate a clean deploy workspace)
      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./target
    
    # Deploy to ACR
      - uses: ./.github/actions/deploy-acr
        with:
          acr-repository: ${{ secrets.ACR_REPOSITORY }}
          acr-username: 'acr-admin-token'
          acr-admin-token: ${{ secrets.ACR_ADMIN_TOKEN }}
          image-name: ${{secrets.IMAGE_NAME}}
          image-tag: 'latest'